availableSecrets:
  secretManager:
  - versionName: projects/voxelphile/secrets/voxelphile_key/versions/latest
    env: 'KEY'
  - versionName: projects/voxelphile/secrets/voxelphile_crt/versions/latest
    env: 'CRT'
steps:
steps:
  - name: 'docker'
    args: [ 'buildx', 'create', '--name', 'mybuilder', '--use' ]
  - name: gcr.io/cloud-builders/docker
    secretEnv: ['KEY', 'CRT']
    args:
      - buildx
      - 'build'
      - '--push'
      - '--platform' 
      - 'linux/arm64'
      - '--build-arg'
      - 'ARG_KEY=$$KEY'
      - '--build-arg'
      - 'ARG_CRT=$$CRT'
      - '-t'
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-gke-source-deploy/$REPO_NAME:$COMMIT_SHA'
      - '-f'
      - $_DOCKERFILE_NAME
    dir: $_DOCKERFILE_DIR
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_AR_HOSTNAME/$PROJECT_ID/cloud-gke-source-deploy/$REPO_NAME:$COMMIT_SHA'
    id: Push
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - prepare
      - '--filename=$_K8S_YAML_PATH'
      - '--image=$_AR_HOSTNAME/$PROJECT_ID/cloud-gke-source-deploy/$REPO_NAME:$COMMIT_SHA'
      - '--app=$_K8S_APP_NAME'
      - '--version=$COMMIT_SHA'
      - '--namespace=$_K8S_NAMESPACE'
      - '--label=$_K8S_LABELS'
      - '--annotation=$_K8S_ANNOTATIONS,gcb-build-id=$BUILD_ID'
      - '--create-application-cr'
      - >-
        --links="Build
        details=https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=$PROJECT_ID"
      - '--output=output'
    id: Prepare deploy
  - name: gcr.io/cloud-builders/gsutil
    args:
      - '-c'
      - |-
        if [ "$_OUTPUT_BUCKET_PATH" != "" ]
        then
          gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/suggested
          gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET_PATH/config/$_K8S_APP_NAME/$BUILD_ID/expanded
        fi
    id: Save configs
    entrypoint: sh
  - name: gcr.io/cloud-builders/gke-deploy
    args:
      - apply
      - '--filename=output/expanded'
      - '--cluster=$_GKE_CLUSTER'
      - '--location=$_GKE_LOCATION'
      - '--namespace=$_K8S_NAMESPACE'
    id: Apply deploy
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-gke-source-deploy/$REPO_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _K8S_ANNOTATIONS: gcb-trigger-id=b2e7e9e2-7414-41eb-9f9b-9898fbf5b74f
  _GKE_CLUSTER: albert-einstein
  _OUTPUT_BUCKET_PATH: voxelphile_cloudbuild/deploy
  _GKE_LOCATION: us-central1-a
  _K8S_YAML_PATH: kubernetes/
  _K8S_NAMESPACE: sol
  _K8S_APP_NAME: sol
  _DOCKERFILE_DIR: ''
  _DOCKERFILE_NAME: Dockerfile
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _K8S_LABELS: ''
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
