availableSecrets:
  secretManager:
  - versionName: projects/voxelphile/secrets/voxelphile_key/versions/latest
    env: 'KEY'
  - versionName: projects/voxelphile/secrets/voxelphile_crt/versions/latest
    env: 'CRT'
steps:
  - name: ubuntu:latest
    secretEnv: ["KEY", "CRT"]
    entrypoint: "bash"
    args:
      - '-c'
      - |
        echo $$KEY > ./key \
        && echo $$CRT > ./crt \
        && apt-get update -y \
        && apt-get -y install apt-transport-https ca-certificates curl make software-properties-common gnupg \
        && install -m 0755 -d /etc/apt/keyrings \
        && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
        && chmod a+r /etc/apt/keyrings/docker.gpg \
        && echo "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu   "$(. /etc/os-release && echo "$$VERSION_CODENAME")" stable" |   tee /etc/apt/sources.list.d/docker.list > /dev/null \
        && apt-get update -y \
        && apt-get -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin \
        && ls . \
        && docker buildx create --use --name multi-arch-builder \
        && docker buildx build --platform linux/arm64 --squash --push -t $_AR_HOSTNAME/$PROJECT_ID/cloud-gke-source-deploy/$_K8S_APP_NAME:$COMMIT_SHA -t $_AR_HOSTNAME/$PROJECT_ID/cloud-gke-source-deploy/$_K8S_APP_NAME:latest /workspace/
    id: Build
    dir: $_DOCKERFILE_DIR
  - name: google/cloud-sdk:latest
    entrypoint: "bash"
    args:
      - -c
      - |
        apt-get update -y 
        && for file in /workspace/kubernetes/*.yaml; do envsubst < $file | kubectl apply -f -; done
    id: Apply / Deploy
    env:
    - CLOUDSDK_COMPUTE_ZONE=$_GKE_LOCATION
    - CLOUDSDK_CONTAINER_CLUSTER=$_GKE_CLUSTER
    - _K8S_IMAGE=$_K8S_APP_NAME=$_AR_HOSTNAME/$PROJECT_ID/cloud-gke-source-deploy/$_K8S_APP_NAME:$COMMIT_SHA
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-gke-source-deploy/$REPO_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _K8S_ANNOTATIONS: gcb-trigger-id=b2e7e9e2-7414-41eb-9f9b-9898fbf5b74f
  _GKE_CLUSTER: albert-einstein
  _OUTPUT_BUCKET_PATH: voxelphile_cloudbuild/deploy
  _GKE_LOCATION: us-central1-a
  _K8S_YAML_PATH: kubernetes/
  _K8S_NAMESPACE: sol
  _K8S_APP_NAME: sol
  _DOCKERFILE_DIR: '/workspace'
  _DOCKERFILE_NAME: Dockerfile
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _K8S_LABELS: ''
tags:
  - gcp-cloud-build-deploy
  - $_K8S_APP_NAME
